#!/usr/bin/env bash

# Automated Arch Install (arch-chroot part)

# Settings
INSTALL_HOSTNAME=gonzo-vm
INSTALL_USERNAME=starquake

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# exit when any command fails
set -exuo pipefail

# Configure Time-related settings
ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
hwclock --systohc

# Set up locales
tee /etc/locale.gen >/dev/null <<EOF
en_US.UTF-8 UTF-8
nl_NL.UTF-8 UTF-8
EOF

locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Set hostname
echo $INSTALL_HOSTNAME >/etc/hostname

# Configure and run mkinitcpio
sed -i 's/^HOOKS=(\(.*\))$/HOOKS=(\1 plymouth)/' /etc/mkinitcpio.conf
mkinitcpio -P

# Add the first user
useradd -m -G wheel $INSTALL_USERNAME

# Install systemd-boot loader
bootctl install 

tee /boot/loader/loader.conf >/dev/null <<EOF
default  arch-lts.conf
# timeout  0
EOF

tee /boot/loader/entries/arch-lts.conf >/dev/null <<EOF
title   Arch Linux (LTS)
linux   /vmlinuz-linux-lts
initrd  /amd-ucode.img
initrd  /initramfs-linux-lts.img
options root="LABEL=arch_os" rw splash quiet
EOF

tee /boot/loader/entries/arch-lts-fallback.conf >/dev/null <<EOF
title   Arch Linux (LTS, fallback)
linux   /vmlinuz-linux-lts
initrd  /amd-ucode.img
initrd  /initramfs-linux-lts-fallback.img
options root="LABEL=arch_os" rw splash quiet
EOF

# Enable systemd-boot update service
systemctl enable systemd-boot-update.service

# Enable some more services
systemctl enable gdm
systemctl enable NetworkManager
systemctl enable fstrim.timer

# Configure pacman
sed -i 's/^#\(ParallelDownloads\).*$/\1 = 5/' /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf
# sed -i 's/^#\[multilib\]/\[multilib\]/' /etc/pacman.conf

# Configure makepkg
sed -i 's/^#\(MAKEFLAGS\).*$/\1="--jobs \$\(nproc\)"/' /etc/makepkg.conf

# Set up for AUR and install yay
mkdir "/home/$INSTALL_USERNAME/build"
cd "/home/$INSTALL_USERNAME/build"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

# Install some more packages
yay -S pacman-backup-hook pacman-cleanup-hook informant ttf-ms-win11-auto

# Setup informant
usermod -a -G informant $INSTALL_USERNAME

echo "Done Installing the arch-chroot part"
echo -n
echo "Don't forget to set a password for user ${INSTALL_USERNAME}!"