#!/usr/bin/env bash

# My Automated Arch Install

# Settings
INSTALL_USERNAME=starquake

# Check for root
if [ "$EUID" -eq 0 ]; then
    echo "Please run as a normal user"
    exit
fi

# exit when any command fails
set -exuo pipefail

# Set up for AUR and install yay
mkdir "/home/$INSTALL_USERNAME/build"
cd "/home/$INSTALL_USERNAME/build"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

# Install some more packages
yay -S pacman-backup-hook pacman-cleanup-hook informant ttf-ms-win11-auto etc-update

# Setup informant
sudo usermod -a -G informant $INSTALL_USERNAME